apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  storageClassName: nginx
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi  
  # C:\pod-data
  hostPath:
    path: /run/desktop/mnt/host/c/pod-data 

