apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx:1.23
    name: nginx    
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: web-volume
  volumes:
  - name: web-volume
    hostPath:
      path: /pod-data
      type: Directory