apiVersion: v1
kind: Secret
metadata:
  name: mysecret  
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: ubuntu:22.04
    command: ["/bin/bash", "-ec"]
    args:
    - echo -n 'username:'; 
      cat /etc/secrets/username;
      echo '';
      echo -n 'password:'; 
      cat /etc/secrets/password;
      echo '';
      sleep 600;
    volumeMounts:
    - name: secrets-volume
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: secrets-volume
    secret:
      secretName: mysecret