services: 
  webappanuncios:
    image: mastercloudapps/webapp-anuncios:v1.0
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/anuncios
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=anuncios